# Generated by Django 2.0.4 on 2018-04-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20180322_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumber',
            name='user_session',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
