# Generated by Django 2.0.4 on 2018-04-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_usernumber_user_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
