# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_objectviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='ip_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
