# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
    ]
