# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_pageviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviews',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
