# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20171119_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageviews',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pageviews',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pageviews',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
