# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_usernumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewed',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Object viewed', 'verbose_name_plural': 'Object viewed'},
        ),
        migrations.AlterModelOptions(
            name='pageviews',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Page Views', 'verbose_name_plural': 'Page Views'},
        ),
        migrations.AlterModelOptions(
            name='querylist',
            options={'ordering': ['-date_added'], 'verbose_name': 'Query List', 'verbose_name_plural': 'Query List'},
        ),
        migrations.AlterModelOptions(
            name='usernumber',
            options={'ordering': ['-date_added'], 'verbose_name': 'User Number', 'verbose_name_plural': 'User Number'},
        ),
    ]
