# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20171204_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageviews',
            options={'ordering': ['timestamp'], 'verbose_name': 'Page Views', 'verbose_name_plural': 'Page Views'},
        ),
        migrations.AlterModelOptions(
            name='usernumber',
            options={'ordering': ['date_added'], 'verbose_name': 'User Number', 'verbose_name_plural': 'User Number'},
        ),
    ]
