# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_auto_20171216_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_o', models.CharField(blank=True, max_length=200, null=True)),
                ('time_spent', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
