# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_usertime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertime',
            options={'ordering': ['-id'], 'verbose_name': 'User Time', 'verbose_name_plural': 'User Time'},
        ),
    ]
