# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_auto_20171223_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageviews',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Page Views', 'verbose_name_plural': 'Page Views'},
        ),
        migrations.AlterModelOptions(
            name='usernumber',
            options={'ordering': ['-date_added'], 'verbose_name': 'User Number', 'verbose_name_plural': 'User Number'},
        ),
        migrations.AddField(
            model_name='usertime',
            name='current_page',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
