# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_querylist_baser_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumber',
            name='user_country_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usernumber',
            name='user_country_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
