# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_usernumber_user_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernumber',
            name='user_header',
        ),
    ]
