# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_remove_usernumber_user_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumber',
            name='user_header',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
