# Generated by Django 2.0.3 on 2018-03-22 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='target_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='target_object', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
