# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_agree_to_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
