# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171226_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
