# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
