# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171102_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
