# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171102_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
    ]
