# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171102_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
