# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_clicks', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-number_of_clicks'],
                'verbose_name_plural': 'Analytics',
                'verbose_name': 'Analytics',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feelings', models.IntegerField(blank=True, choices=[(100, 'Extremely satisfied'), (70, 'Moderately satisfied'), (40, 'Slightly satisfied'), (10, 'Neutral'), (5, 'Slightly dissatisfied'), (2, 'Moderately dissatisfied'), (1, 'Exteremely dissatisfied')], null=True)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('url_locator', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(default='', max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('converted_price', models.CharField(blank=True, max_length=300, null=True)),
                ('real_price', models.IntegerField(default=0)),
                ('real_price_2', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, max_length=355, null=True, upload_to='')),
                ('source_url', models.CharField(max_length=700)),
                ('shop', models.CharField(max_length=300)),
                ('country_code', models.CharField(blank=True, max_length=200, null=True)),
                ('num_of_clicks', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('old_price', models.CharField(blank=True, max_length=200, null=True)),
                ('old_price_2', models.CharField(blank=True, max_length=200, null=True)),
                ('old_price_digit', models.IntegerField(default=0)),
                ('old_price_digit_2', models.IntegerField(default=0)),
                ('sub_genre', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subcriptions', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_did_it', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Products',
                'verbose_name': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Tips',
                'verbose_name': 'Tip',
            },
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('theme', models.BooleanField(default=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'User Theme',
                'verbose_name': 'User Theme',
            },
        ),
        migrations.AddField(
            model_name='analytics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findit.Products'),
        ),
    ]
