# Generated by Django 2.0.3 on 2018-03-22 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='product',
            field=models.OneToOneField(on_delete=True, to='findit.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='who_did_it', to=settings.AUTH_USER_MODEL),
        ),
    ]
