# Generated by Django 2.0.3 on 2018-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0002_auto_20180322_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='lppo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
