# Generated by Django 2.0.3 on 2018-03-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0003_products_lppo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findit.Products'),
        ),
    ]
