# Generated by Django 2.0.3 on 2018-03-23 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0004_auto_20180323_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcriptions',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
