# Generated by Django 2.0.3 on 2018-03-23 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0005_auto_20180323_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcriptions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
