# Generated by Django 2.0.4 on 2018-07-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0008_auto_20180612_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, max_length=355, upload_to=''),
            preserve_default=False,
        ),
    ]
