# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findit', '0022_feedback_url_locator'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_did_it', to=settings.AUTH_USER_MODEL),
        ),
    ]
