# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0023_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='num_of_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
