# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0024_products_num_of_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('theme', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
