# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0025_usertheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-id'], 'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='usertheme',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Theme', 'verbose_name_plural': 'User Theme'},
        ),
        migrations.AddField(
            model_name='usertheme',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheme',
            name='theme',
            field=models.BooleanField(default=True, max_length=200),
        ),
    ]
