# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0026_auto_20171205_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytics',
            options={'ordering': ['-number_of_clicks'], 'verbose_name': 'Analytics', 'verbose_name_plural': 'Analytics'},
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, max_length=355, null=True, upload_to=''),
        ),
    ]
