# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0027_auto_20171210_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='source_url',
            field=models.CharField(max_length=700),
        ),
    ]
