# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0028_auto_20171210_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price_digit_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='real_price_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
