# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0029_auto_20171211_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
