# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0030_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='converted_price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
