# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0031_products_converted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='old_price_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='old_price_digit',
        ),
        migrations.RemoveField(
            model_name='products',
            name='old_price_digit_2',
        ),
    ]
