# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0032_auto_20180108_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price_digit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price_digit_2',
            field=models.IntegerField(default=0),
        ),
    ]
