# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0035_auto_20180116_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='country_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
