# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0036_products_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
