# Generated by Django 2.0.4 on 2018-07-29 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='ad_cutomers')),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('date_adder', models.DateField(auto_now_add=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('expired', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=40)),
                ('time_wait', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_type', models.CharField(choices=[('Banner', 'Banner'), ('Products', 'Products')], default='Banner', max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ad_owner', models.ForeignKey(blank=True, null=True, on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='AdsBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('Banner', 'Banner'), ('Products', 'Products')], default='Banner', max_length=200)),
                ('as_ad_credit', models.BooleanField(default=False)),
                ('ad_owner', models.ForeignKey(blank=True, null=True, on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_cal', models.CharField(blank=True, max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('ads', models.ForeignKey(on_delete=True, to='adplace.Ads')),
            ],
            options={
                'verbose_name': 'Clicks',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_cal', models.CharField(blank=True, max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('ads', models.ForeignKey(on_delete=True, to='adplace.Ads')),
            ],
            options={
                'verbose_name': 'Views',
            },
        ),
    ]
